version: '3'
services:

  sensors_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
        - '5432:5432'

  refuapp-sensor-backend:
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - sensors_db:docker-mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: docker-mysql
      DB_PORT: 5432
      REFUGE_ID: ${REFUGE_ID}
      REFUGE_PASSWORD: ${REFUGE_PASSWORD}
    depends_on:
      - sensors_db
    ports:
      - '8000:8000'
